version: '3'

services:
  client: # Name of our service
    build: ./client # path to dockerfile
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    container_name: client-docker
    restart: always # What to do if container crashes
    links:
      - server

  server: 
    build: ./server 
    ports: 
      - "8080:8080"
    container_name: server-docker
    restart: always 
